[build]
builder = "nixpacks"

[deploy]
startCommand = "npm run db:push && npm run start"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[[services]]
name = "posting-app"

[services.variables]
NODE_ENV = "production"